# Generated by Django 3.2.23 on 2023-12-09 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='bulb_amount',
            new_name='bulbamount',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='bulb_type',
            new_name='bulbtype',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='description_1',
            new_name='description1',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='ip_rating',
            new_name='iprating',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='lamp_title',
            new_name='lamptitle',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='lamp_type',
            new_name='lamptype',
        ),
    ]
