# Generated by Django 3.2.23 on 2023-12-09 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_products_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='color',
            new_name='colour',
        ),
    ]
