# Generated by Django 3.2.23 on 2023-12-25 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_color_product_colour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='colour',
            options={'verbose_name_plural': 'Colours'},
        ),
        migrations.AlterModelOptions(
            name='iprating',
            options={'verbose_name_plural': 'IP ratings'},
        ),
        migrations.AlterModelOptions(
            name='lamptype',
            options={'verbose_name_plural': 'Lamp types'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
